using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;

public class Coltroller : MonoBehaviour
{
    public VideoPlayer player;
    public List<VideoClip> clips = new List<VideoClip>();

    int currentIndex = 0;

    public List<int> endButtons_0 = new List<int>();
    public List<int> endButtons_1 = new List<int>();
    public List<int> endButtons_2 = new List<int>();
    public List<int> endButtons_3 = new List<int>();
    public List<int> endButtons_4 = new List<int>();
    public List<int> endButtons_5 = new List<int>();
    public List<int> endButtons_6 = new List<int>();

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }


    public void PlayVideo(int _index)
    {
        
    }

}
